// Bảng mã lỗi — đúng 04-api-contract.md mục 1.2. Mỗi mã: HTTP status + message tiếng Việt mặc định.
export const ERROR_CODES = {
  VALIDATION_ERROR: { status: 400, message: 'Dữ liệu gửi lên không hợp lệ.' },
  UNAUTHORIZED: { status: 401, message: 'Bạn cần đăng nhập.' },
  TOKEN_EXPIRED: { status: 401, message: 'Phiên đăng nhập đã hết hạn.' },
  INVALID_CREDENTIALS: { status: 401, message: 'Email hoặc mật khẩu không đúng.' },
  FORBIDDEN: { status: 403, message: 'Bạn không có quyền thực hiện thao tác này.' },
  ACCOUNT_DISABLED: { status: 403, message: 'Tài khoản đã bị khóa.' },
  NOT_FOUND: { status: 404, message: 'Không tìm thấy dữ liệu.' },
  EMAIL_EXISTS: { status: 409, message: 'Email này đã được đăng ký.' },
  SEAT_UNAVAILABLE: { status: 409, message: 'Một số ghế vừa có người chọn, vui lòng chọn ghế khác.' },
  ORDER_NOT_PENDING: { status: 409, message: 'Đơn hàng không còn ở trạng thái chờ thanh toán.' },
  SHOWTIME_OVERLAP: { status: 409, message: 'Suất chiếu bị trùng giờ trong cùng phòng.' },
  RESOURCE_IN_USE: { status: 409, message: 'Dữ liệu đã có lịch sử sử dụng nên không thể xóa.' },
  TICKET_ALREADY_USED: { status: 409, message: 'Vé đã được sử dụng.' },
  ORDER_EXPIRED: { status: 410, message: 'Đơn hàng đã quá hạn giữ ghế.' },
  SHOWTIME_CLOSED: { status: 422, message: 'Suất chiếu đã đóng bán vé.' },
  SEAT_LIMIT_EXCEEDED: { status: 422, message: 'Mỗi đơn chỉ được chọn tối đa 8 ghế.' },
  COUPLE_SEAT_INCOMPLETE: { status: 422, message: 'Ghế đôi phải chọn đủ cả hai ghế.' },
  PROMO_INVALID: { status: 422, message: 'Mã khuyến mãi không dùng được.' },
  TICKET_NOT_PAID: { status: 422, message: 'Đơn hàng chưa thanh toán.' },
  CHECKIN_NOT_ALLOWED: { status: 422, message: 'Chưa/đã quá giờ cho phép check-in.' },
  RATE_LIMITED: { status: 429, message: 'Bạn thao tác quá nhiều lần, vui lòng thử lại sau.' },
  INTERNAL_ERROR: { status: 500, message: 'Có lỗi hệ thống, vui lòng thử lại sau.' },
};
